package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Dealer;
import org.mybatis.cdi.Mapper;

@Mapper
public interface DealerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEALER
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEALER
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    int insert(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEALER
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    Dealer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEALER
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    List<Dealer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEALER
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    int updateByPrimaryKey(Dealer record);
}