package lt.vu.mybatis.model;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.LEASING_PRICE
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    private Integer leasingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MAKE
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    private String make;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MODEL
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.DEALER_ID
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    private Integer dealerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.PRICE
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.LEASING_PRICE
     *
     * @return the value of PUBLIC.CAR.LEASING_PRICE
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public Integer getLeasingPrice() {
        return leasingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.LEASING_PRICE
     *
     * @param leasingPrice the value for PUBLIC.CAR.LEASING_PRICE
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public void setLeasingPrice(Integer leasingPrice) {
        this.leasingPrice = leasingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MAKE
     *
     * @return the value of PUBLIC.CAR.MAKE
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public String getMake() {
        return make;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MAKE
     *
     * @param make the value for PUBLIC.CAR.MAKE
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public void setMake(String make) {
        this.make = make;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MODEL
     *
     * @return the value of PUBLIC.CAR.MODEL
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MODEL
     *
     * @param model the value for PUBLIC.CAR.MODEL
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.DEALER_ID
     *
     * @return the value of PUBLIC.CAR.DEALER_ID
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.DEALER_ID
     *
     * @param dealerId the value for PUBLIC.CAR.DEALER_ID
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.PRICE
     *
     * @return the value of PUBLIC.CAR.PRICE
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.PRICE
     *
     * @param price the value for PUBLIC.CAR.PRICE
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}