package lt.vu.mybatis.model;

public class Dealer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEALER.ID
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEALER.NAME
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEALER.ID
     *
     * @return the value of PUBLIC.DEALER.ID
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEALER.ID
     *
     * @param id the value for PUBLIC.DEALER.ID
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEALER.NAME
     *
     * @return the value of PUBLIC.DEALER.NAME
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEALER.NAME
     *
     * @param name the value for PUBLIC.DEALER.NAME
     *
     * @mbg.generated Mon May 30 19:29:03 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}